project:
  type: default

title: "Prijava EU Projekta"
author: "Sveučilište u Zagrebu, Građevinski fakultet"
date: today
date-format: "DD.MM.YYYY"

bibliography: references.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl

format:
  pdf:
    documentclass: article
    papersize: a4
    geometry:
      - top=25mm
      - left=25mm
      - right=25mm
      - bottom=25mm
    include-in-header: custom-header.tex
    fontsize: 11pt
    mainfont: Arial
    number-sections: true
    toc: true
    toc-title: Sadržaj
    colorlinks: true
  docx:
    number-sections: true
    toc: true
